#!/bin/sh -e

TRIGGERING_NEXT_BUILD=true

. CI/travis/lib.sh

should_trigger_next_builds "$TRAVIS_BRANCH" || exit 0

trigger_adi_build "gr-iio" "$TRAVIS_BRANCH"
trigger_adi_build "iio-oscilloscope" "$TRAVIS_BRANCH"
