#!/bin/sh

brew update
if ! brew ls --version cmake &>/dev/null; then
	brew install cmake
else
	brew upgrade cmake
fi
brew install doxygen
brew install --build-from-source libusb
brew install libxml2

wget http://swdownloads.analog.com/cse/travis_builds/master_latest_libiio${LDIST}.pkg
sudo installer -pkg master_latest_libiio${LDIST}.pkg -target /
