#!/bin/sh -xe

. CI/travis/lib.sh

sudo apt-get -qq update
sudo apt-get install -y cmake doxygen libaio-dev libavahi-client-dev libavahi-common-dev libusb-1.0-0-dev libxml2-dev rpm tar bzip2 gzip
if [ `sudo apt-cache search libserialport-dev | wc -l` -gt 0 ] ; then
	sudo apt-get install -y libserialport-dev
fi

wget http://swdownloads.analog.com/cse/travis_builds/${LIBIIO_BRANCH}_latest_libiio${LDIST}.deb
sudo dpkg -i ./${LIBIIO_BRANCH}_latest_libiio${LDIST}.deb
