#!/bin/sh -e

if [ "x${COVERITY_SCAN_PROJECT_NAME}" != "x" ] ; then exit 0; fi

mkdir -p build

cd build
cmake -DOSX_PACKAGE=ON -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Release}" ..
make
ls
make test

cd ..

mkdir -p build_tar

cd build_tar
cmake -DOSX_PACKAGE=OFF -DENABLE_PACKAGING=ON -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Release}" ..
make
ls
make package
make test
