name: ARM Builds

on:
  workflow_call:
    inputs:
      download_branch:
        required: true
        type: string
      checkout_ref:
        required: false
        type: string
        default: ''

permissions:
  contents: read

jobs:
  arm-builds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-ppc64le
            image: tfcollins/libiio_ubuntu_20_04-ci-arm-ppc:latest
            arch: ppc64le
            build_script: ci-ubuntu.sh
            artifactName: 'Ubuntu-ppc64le'
          - name: ubuntu-x390x
            image: tfcollins/libiio_ubuntu_20_04-ci-arm-ppc:latest
            arch: s390x
            build_script: ci-ubuntu.sh
            artifactName: 'Ubuntu-x390x'
          - name: debian_buster_arm32v7
            image: tfcollins/libiio_ubuntu_20_04-ci-arm-ppc:latest
            arch: arm
            build_script: ci-ubuntu.sh
            artifactName: 'Ubuntu-arm32v7'
          - name: debian_buster_arm64v8
            image: tfcollins/libiio_ubuntu_20_04-ci-arm-ppc:latest
            arch: aarch64
            build_script: ci-ubuntu.sh
            artifactName: 'Ubuntu-arm64v8'
          - name: debian_bookworm_arm
            image: tfcollins/libiio_debian_bookworm-ci-arm-ppc:latest
            arch: arm
            build_script: ci-ubuntu.sh
            artifactName: 'Debian12-arm'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.checkout_ref }}
          fetch-depth: 1

      - name: Download libiio build artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: analogdevicesinc/libiio
          workflow: build.yml
          workflow_conclusion: success
          branch: ${{ inputs.download_branch }}
          name: ${{ matrix.artifactName }}
          path: ${{ github.workspace }}/build/
          if_no_artifact_found: fail

      - name: Setup
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install qemu-user-static
          sudo sysctl kernel.randomize_va_space=0
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build
        run: |
          set -e
          sudo docker run --platform "linux/${{ matrix.arch }}" --rm -t --privileged \
            -e ARTIFACTNAME=${{ matrix.artifactName }} \
            -v "${{ github.workspace }}":"/ci" \
            -v "/usr/bin/qemu-${{ matrix.arch }}-static":"/usr/bin/qemu-${{ matrix.arch }}-static" \
            "${{ matrix.image }}" \
            /bin/bash -c "cd /ci/ && chmod +x ./CI/travis/${{ matrix.build_script }} && ./CI/travis/${{ matrix.build_script }}"

      - name: Publish build artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifactName }}
          path: |
            ${{ github.workspace }}/build/*.deb
            ${{ github.workspace }}/build/*.rpm
          if-no-files-found: ignore
